---

global:
  scrape_interval: '10s'
  evaluation_interval: '10s'

alerting:
  alertmanagers: []

remote_write: []

rule_files: []

scrape_configs:
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch_exporter:9114']
