{
 "title": "Exemples visualisations",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "label_values(up, job)" }
  ]
 },
 "panels": [
  { "title": "Concepts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Datasource mixed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scrape_samples_scraped < 100" },
    {}
   ]
  },
  {
   "title": "Variables",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scrape_samples_scraped{job=~\"$job\"}",
     "legendFormat": "{{job }} ( {{instance}} )"
    }
   ]
  },
  {
   "title": "Dashboard datasource",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "panelId": 4 }
   ]
  },
  { "title": "Repeat Panel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Scraped values for $job",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "repeat": "Job",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "scrape_samples_scraped{job=~\"$job\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Reapeat Row - $job - Scrapped series",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "repeat": "job"
  },
  {
   "title": "Last scraped sample",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(scrape_samples_scraped{job=~\"$job\"}) by (job)",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Scraped history",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scrape_samples_scraped{job=~\"$job\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Series added",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(scrape_series_added{job=~\"$job\"}) by (job)",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Reapeat Row - $job - Scrapped series",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }
  },
  {
   "title": "Last scraped sample",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(scrape_samples_scraped{job=~\"$job\"}) by (job)",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Scraped history",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scrape_samples_scraped{job=~\"$job\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Series added",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(scrape_series_added{job=~\"$job\"}) by (job)",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Visualisations (not linked to Job)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 }
  },
  {
   "title": "Graph",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(\n  0.5,\n  sum by(le) (\n    rate(\n      flask_http_request_duration_seconds_bucket[5m]\n    )\n  )\n), \"quantile\", \"0.5\", \"\", \"\")",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "label_replace(histogram_quantile(\n  0.9,\n  sum by(le) (\n    rate(\n      flask_http_request_duration_seconds_bucket[5m]\n    )\n  )\n), \"quantile\", \"0.9\", \"\", \"\")",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Series overrides",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum [5m]))",
     "legendFormat": "Duration"
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count [5m]))",
     "legendFormat": "Requetes"
    }
   ]
  },
  {
   "title": "Brouillard",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(flask_http_request_duration_seconds_bucket{status=\"200\", method=\"GET\"}[5m]))",
     "legendFormat": "avg"
    },
    {
     "expr": "min(rate(flask_http_request_duration_seconds_bucket{status=\"200\", method=\"GET\"}[5m]))",
     "legendFormat": "min"
    },
    {
     "expr": "max(rate(flask_http_request_duration_seconds_bucket{status=\"200\", method=\"GET\"}[5m]))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Histogramme",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_bucket[1m])"
    }
   ]
  },
  {
   "title": "Table with filters and transforms",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "targets": [
    { "expr": "scrape_samples_scraped" }
   ]
  },
  {
   "title": "Bar gauge",
   "type": "bargauge",
   "description": "Samples scrapped",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort(sum(scrape_samples_scraped) by (job))",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Negative Y viz",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total [5m]))",
     "legendFormat": "Transmit"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total [5m]))",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Load 5",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load5", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Load 15",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load15", "legendFormat": "{{ instance }}" }
   ]
  },
  { "title": "Current alerts", "type": "alertlist", "gridPos": { "h": 10, "w": 4, "x": 16, "y": 50 } },
  { "title": "Alerts changes", "type": "alertlist", "gridPos": { "h": 10, "w": 4, "x": 20, "y": 50 } }
 ]
}